dataset:
  spacing: [1.0, 1.0, 1.0] # [x, y, z], mm
  value_range: [-500, 1024] # [min, max], HU scale
  resolution: [512, 512, 512] # [x, y, z]
  block_size: [32, 32, 32] # [x, y, z]
  zoom_size: [128,128,128]
  mask_range: [0, 1]

projector:
  n_porjections: 2

  # system configuration
  DSD: 1200 # distance source detector (mm)
  DSO: 800  # distance source origin   (mm)

  # detector parameters
  nDetector: [128, 128] # number of pixels (px)
  dDetector: [1.5, 1.5] # size of each pixel (mm)

  # image parameters
  nVoxel: [128, 128, 128] # number of voxels (vx) [x, y, z]
  dVoxel: [1.0, 1.0, 1.0] # size of each voxel (mm)

  # offsets
  offOrigin: [0, 0, 0] # offset of image from origin (mm) [x, y, z]
  offDetector: [0, 0] # offset of detector (only in two direction) (mm) [u, v]

  # Auxiliary
  accuracy: 0.5 # accuracy of FWD proj (vx/sample)

  # Mode
  mode: cone # x-ray source mode parallel/cone
  filter: null

  # Angles
  total_angle: 180 # total angle (degree)
  start_angle: 0   # start angle (degree)